language: java
install: true
script: if [[ "$TRAVIS_REPO_SLUG" == "immutables/immutables" && "$TRAVIS_BRANCH" == "master" && "$TRAVIS_EVENT_TYPE" != "pull_request" ]]; then mvn deploy -Dlint-javadoc -DdeployAtEnd=true --settings settings.xml; else mvn package; fi
sudo: false
cache:
  directories:
  - $HOME/.m2
jdk:
  - openjdk8
